version: '3'

services:
  mysqldb:
    build:
      context: ./build/mysqldb
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    ports:
      - "${HOST_DB_PORT}:3306"
    volumes:
      - ./build/mysqldb/seed:/docker-entrypoint-initdb.d
      - ./build/mysqldb/data:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
    restart: 'always'
    container_name: 'mysqldb'
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mysqldb
    #  - PMA_USER=${DB_USER}
    #  - PMA_PASSWORD=${DB_PASSWORD}
      - PMA_ARBITRARY=1
    ports:
      - "9090:80"
    restart: 'always'
    container_name: 'phpmyadmin'
  php-fpm:
    build:
      context: ./build/php-fpm
    depends_on:
      - mysqldb
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=mysql://${DB_USER}:${DB_PASSWORD}@mysqldb:3306/${DB_NAME}
    volumes:
      - ./src:/var/www
      #- ./build/php-fpm/php.ini:/usr/local/etc/php/conf.d/docker-php-config.ini
    restart: 'always'
    container_name: 'php-fpm'
    user: ${HOST_USER}
  nginx:
    build:
      context: ./build/nginx
    volumes:
      - ./src:/var/www
      - ./build/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./build/nginx/sites/:/etc/nginx/sites-available
      - ./build/nginx/conf.d/:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - php-fpm
    ports:
      - "${HOST_HTTP_PORT}:80"
      - "${HOST_HTTPS_PORT}:443"
    restart: 'always'
    container_name: 'nginx'
